language: node_js
git:
  depth: 3
branches:
  only:
  - master
node_js:
  - 6.1.0
env:
  global:
    - NODE_ENV=production
before_install:
  # - npm run init
  - sudo apt-get update -qq
install: true
before_script:
  - npm install -g react-native gulp
  - npm install
script:
  - cd mobile/ && ./build-mobile.sh && cd ..
  - cd server/client && build-client.sh
sudo: false    
