language: android

env:
  global:
    - CXX=g++-4.9
    - TRAVIS_NODE_VERSION="6.5.0"
    - NODE_ENV=production

node_js:
  - 6.5.0

android:
  components:
    - build-tools-23.0.1
    - android-23
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

git:
  depth: 3

branches:
  only:
    - master

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - node_modules

install:
  #- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  #- sudo apt-get install -y nodejs
  - nvm install 6.5.0
  - node -v
  - npm -v
  #- sudo add-apt-repository -y ppa:chris-lea/node.js
  #- sudo apt-get -y update
  #- sudo apt-get -y install nodejs

# Emulator Management: Create, Start and Wait
before_script:
  #- npm install -g react-native-cli gulp
  - android list targets
  - android list sdk --extended --no-ui --all
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-google_apis-23,sys-img-x86_64-google_apis-23
  - android list targets
  - echo no | android create avd --force -n test-device-9-x86 -t 9 --abi google_apis/x86_64
  #- echo no | android create avd --force -n test-device-18-x86 -t 48 --abi google_apis/x86_64
  - emulator -avd test-device-9-x86 -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./mobile/build-mobile.sh
  - ./server/client/build-client.sh

#sudo: false
