language: node_js
node_js:
  - 6.1.0
env:
  global:
    - NODE_ENV=production
before_install:
  # - npm run init
before_script:
  # - bower install
  # - gulp
  # - npm install
script:
  - npm install -g react-native
  - npm install -g gulp
  - ./server/client/build-client.sh
  - cd mobile/ && ./build-mobile.sh
sudo: false    
