mongodata:  
  image: mongo:3.3.11
  volumes:
    - /data/db
  command: --break-mongo
mongo:  
  build: db
  volumes_from:
    - mongodata
  ports:
    - "27017:27017"
  command: --smallfiles --rest --auth 
    
api:
  build: server
  links:
    - mongo:db.mongo.com.docker
  restart: always
  command: node server.js
  ports:
    - "3000:3000"
  environment:
    PORT: 3000
  